# Generated by Django 4.2.5 on 2023-09-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_books', '0002_alter_author_slug_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_authors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_books',
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to='e_books.user'),
        ),
    ]
