# Generated by Django 4.2.5 on 2023-09-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_books', '0003_remove_user_favorite_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
